#######################################################################################
# Book settings
title                       : pymetager
author                      : Giacomo Barone, BuildNN
copyright                   : "2020 BuildNN Srl."  # Copyright year to be placed in the footer
logo                        : "_static/logo.svg"  # A path to the book logo
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["exclude/*.ipynb"]  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

sphinx:
  extra_extensions:
  - sphinx_click.ext
  - sphinx.ext.autodoc
  - sphinx.ext.autosummary
  - sphinx.ext.napoleon
